# fly.toml app configuration file generated for deepgram-discord-bot on 2023-07-27T10:31:51+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "deepgram-discord-bot"
primary_region = "yul"

kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0